### ISSUE TITLE
Weird behavior with Canvas Renderer

### ISSUE THREAD

**Issue by Pikalyx** [AntoineThebaud/Reworkbench#1]
When I use the resource pack with Canvas Renderer, I get extreme darkness when I'm in a cave. This is regardless of gamma level as well. 

![2021-12-19_12 33 39](https://user-images.githubusercontent.com/78184925/146684876-e5750258-d7d7-4b29-9f51-9e0828aca985.png)

When I use other resource packs like Mizuno 16, they work normally. 

![2021-12-19_12 37 24](https://user-images.githubusercontent.com/78184925/146684923-d871eafd-736d-45ae-adef-dbefd8d551d1.png)

I'm not sure why this is, but it would be nice if the pack worked with Canvas.

**Comment by AntoineThebaud** [comment]
Hello Pikalyx ! Thanks for your comment

I dont know what is Canvas Renderer but this is actually intended to have darker cave & night light with Reworkbench.

But if you dont like it you can remove the custom light texture from the pack : to do this, open the texture pack archive in winRAR, go to `assets\minecraft\optifine\lightmap\` and delete the file **world0.png**.

**Comment by Pikalyx** [comment]
Oh Thank you! I never noticed that it was intended to be darker. And it fixed the issue I had.

Canvas Renderer is another rendering engine mod like Sodium, but works differently.
