### ISSUE TITLE
What is the License of this project?

### ISSUE THREAD

**Issue by AldeRoberge** [AntoineThebaud/Reworkbench#2]
Hello AntoineThebaud!

I wanted to know if I could use your work for my own game :)
I was wondering, what is the license of this project?

Maybe consider adding a license file (LICENSE.md), like the readme.

https://creativecommons.org/licenses/by/2.0/

**Comment by AntoineThebaud** [comment]
Hello @AldeRoberge, thanks for the suggestion! That was indeed missing, I just [added](https://github.com/AntoineThebaud/Reworkbench/commit/483dde6bcdfa72d3ca088ce0aba4d3b00d17ea5b) a CC-BY-4.0 license to the project.

**Comment by AntoineThebaud** [comment]
Is there a place where to follow the progress of your game? I'd be interested :)

**Comment by AldeRoberge** [comment]
Hey Antoine! I hope you are doing well :) 

Thanks for the quick answer,

You can follow the progress here : https://aliengarden.com/newsletter

You can join me on Discord if you want :)  Alde#5278

Cheers!

**Comment by AntoineThebaud** [comment]
Awesome, thanks! That looks promising :)
